= Nespresso Capsule Vending Machine over Lightning Network

== What is it?

This repository is part of a Do-It-Yourself vending machine project which connects to a Bitcoin point of sales terminal. +
Select your coffee, pay with Bitcoin (via Lightning Network), and the vending machine will deliver your Nespresso capsule.

This repository is the Bitcoin point of sale terminal code for the simple non-BTCPay version of https://github.com/bitcoin-studio/LightningNespressoServer[LightningNespressoServer].

When an invoice has been paid, the server notifies the client via websocket and sends a request to the vending machine which delivers the Nespresso capsule.

* master branch is for a server hosted remotely
* rpi branch is for Raspberry Pi hosting server locally


== See also

* The point of sale website: https://coffee.bitcoin-studio.com
* The vending machine code: https://github.com/bitcoin-studio/LightningNespressoServer[LightningNespressoServer]
* The 3D printed / laser cutted vending machine: https://www.thingiverse.com/thing:3772726[CAD files]
* A description of the project: https://www.bitcoin-studio.com/resources[Bitcoin Studio website]
