= Nespresso Capsule Vending Machine over Lightning Network

== What is it?

This repository is part of a Do-It-Yourself vending machine project which connects to a Bitcoin point of sales terminal. +
Select your coffee, pay with Bitcoin (via Lightning Network), and the vending machine will deliver your Nespresso capsule.

This repository is the Bitcoin point of sale terminal code for the simple non-BTCPay version of https://github.com/bitcoin-studio/LightningNespressoServer[LightningNespressoServer].

When an invoice has been paid, the server notifies the client via websocket and sends a request to the vending machine which delivers the Nespresso capsule.

* master branch is for a server hosted remotely
* rpi branch is for Raspberry Pi hosting server locally


== Notes

Since PWA apps only works with HTTPS, I use HTTPS even in development. Valid `server.crt` and `server.key` files are needed at the root of
the project. You can follow this tutorial to generates them https://medium.com/@tbusser/creating-a-browser-trusted-self-signed-ssl-certificate-2709ce43fd15


== See also

* The point of sale website: https://coffee.bitcoin-studio.com
* The vending machine code: https://github.com/bitcoin-studio/LightningNespressoServer[LightningNespressoServer]
* The 3D printed / laser cutted vending machine: https://www.thingiverse.com/thing:3772726[CAD files]
* A description of the project: https://www.bitcoin-studio.com/resources[Bitcoin Studio website]


== OpenFaaS

=== Templates

.Production Typescript Template
 faas template pull https://github.com/Janaka-Steph/openfaas-template-typescript

.Development Typescript Template
 faas template pull https://github.com/Janaka-Steph/openfaas-template-typescriptdev

=== Secrets

Configuration variables are stored in `.env` file. +
Also, make sure OPENFAAS_URL env var is set properly before running `faas` commands.

 faas secret create lightning-nespresso-api-config --from-file=./api/.env

=== Developing with Okteto

.Make sure the prod image is deployed
 faas up --regex api

.Build a dev image
 DEV=dev faas build --regex api

.Push that image to Okteto container registry
 DEV=dev faas push --regex api

.Sync local source code with remote using dev image
 cd function
 okteto up